<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "onm_cropimages"
 *
 * Auto generated by Extension Builder 2013-03-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Crop Images',
	'description' => 'Crops Images gernerated by Typo3 using the Jcrop jQuery-Plugin',
	'category' => 'plugin',
	'author' => 'Thomas Prangenberg',
	'author_email' => 'tpb@onm.de',
	'author_company' => 'ONM',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>